### ISSUE TITLE
do you consider add security and send messages to special user

### ISSUE THREAD

**Issue by keryhu** [thangufo/spring-angular2-realtime-dashboard#2]
Hi, this is a good example ..

recently ,i try to use websocket and angular2 , spring can send messages publish/subscribe,

but met problems with sending messages to special user.

Don't know if you will consider adding this feature？ or give some suggestion

**Comment by thangufo** [comment]
Hi,
It's trivial to send to an user. In this example, I'm using convertAndSend() to broadcast to all users, you can use convertAndSendToUser to send to a specific user.

**Comment by keryhu** [comment]
HI, @thangufo 
I still struggling with this , the major problem is -
I use stateless security . user access secured url must carry token header every time .

because the login page is in the front,I have to use stateless session,

 when the connection to websocket endpoint is 401 err,and  principal  is null ,,
I do not know : How angular2 stomp connect secured spring socket endpoint?

Do not know if you have any suggestions ？
